title: Making a phone call from a web app
description: You make a phone call from a web app to a PSTN handset.
products:
  - client-sdk

introduction: 
  title: Introduction to this task
  description: This task shows you how to use make a phone call from a web app using the JavaScript Client SDK.
  content: |
    # Introduction
    You will create a Client SDK application and then write the code to make a phone call from your web app to a PSTN phone.

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-node-client-sdk-beta

tasks:
- client-sdk/create-application
- client-sdk/generate-jwt

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    You can do a lot more with the Client SDK.

    See [Client SDK documentation](/client-sdk/overview).
