title: Making a phone call from a web app
description: You make a phone call from a web app to a PSTN handset.
products:
  - client-sdk

introduction: 
  title: Introduction to this task
  description: This task shows you how to use make a phone call from a web app using the JavaScript Client SDK.
  content: |
    # Introduction
    You will create a Client SDK application and then write the code to make a phone call from your web app to a 
    PSTN phone.

    There are several parts required for this solution. You need to create a webhook server that can process an 
    inbound webhook. You need the web application itself that will make the voice call using the functionality 
    of the Client SDK. You also need an NCCO to forward the inbound voice call to the destination phone.

    The web application makes a call to the destination phone. The resultant webhook handler extracts the destination 
    phone number from the answer webhook query parameters and then forwards the call to the destination phone 
    via an NCCO action.


prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-local-web-server
- install-node-client-sdk-beta
- run-ngrok

tasks:
- client-sdk/create-application
- client-sdk/create-user
- client-sdk/generate-jwt
- client-sdk/create-webhook-server
- client-sdk/app-to-phone-code
- client-sdk/run-application

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    You can do a lot more with the Client SDK.

    See [Client SDK documentation](/client-sdk/overview).
