# Hanselminutes Landing Page Config

title: "Thanks, Scott. We'll take it from here!"
meta_title: "Hanselminutes listeners meta-title"

rows:
  - columns:
    - entries: 
      - type: header
        header:
          title: "Thanks, Scott. We'll take it from here!"
          center_title: true
          subtitle: "Welcome, Hanselminutes listeners. Here is everything you need to build your connected applications."
          center_subtitle: true
          subtitle_type: "large"
          icon: "icon-star"
          icon_color: "yellow"
      - type: action_button
        action_button:
          text: "Try it Free"
          url: "sign-up?#ref=hansel-dr"
          type: "secondary"
          large: true
          center_button: true
  - columns:
    - entries:
        - type: line_divider
  - columns:
    - width: 2
      entries:
      - type: call_to_action
        call_to_action:
          title: "SDKs & Tools"
          subtitle: "The Nexmo libraries allow you to get up and running with Nexmo APIs quickly in your language of choice."
          icon: "icon-design-tools"
          icon_color: "blue-dark"
          url: "/tools"
    - width: 2
      entries:
      - type: call_to_action
        call_to_action:
          title: "Community"
          subtitle: "Find out about our talks, community hacks, and what events we'll be at."
          icon: "icon-group"
          icon_color: "blue-dark"
          url: "/community"
  - columns:
    - entries:
        - type: line_divider
  - columns:
    - entries:
      - type: join_slack
  - columns:
    - entries:
        - type: line_divider
  - columns:
    - entries:
      - type: call_to_action
        call_to_action:
          title: "Nexmo & .NET in action"
          subtitle: "The Nexmo libraries allow you to get up and running with<br>Nexmo APIs quickly in your language of choice.<br><br>"
          large_text: "Examples and inspiration in .NET form"
          icon: "Brand-icon-dotnet"
          icon_color: "blue-dark"
          url: "https://www.nexmo.com/blog/category/developer?ref=hansel-dr"
  - columns:
    - width: 2
      entries:
      - type: tutorial
        tutorial:
          name: two-factor-authentication-dotnet-verify-api
    - width: 2
      entries:
      - type: tutorial
        tutorial:
          name: number-insight-api-aspnet
  - columns: 
    - entries:
      - type: github_repo
        github_repo:
          repo_url: https://github.com/Nexmo/nexmo-dotnet
          github_repo_title: "Nexmo REST API client for .NET"
          language: "C#"
  - columns:
    - entries:
      - type: line_divider
  - columns:
    - entries:
      - type: products
  - columns:
    - entries: 
      - type: line_divider
  - columns:
    - entries:
      - type: structured_text
        structured_text:
          header: "Do you have a question?"
          icon: 
          icon_color:
          center_text: true
          text:
            - content: "We're always here to help. Check out our [support FAQs](https://help.nexmo.com/), contact our super helpful [support team](https://help.nexmo.com/hc/en-us/requests/new) or get in touch on [Stack Overflow](http://stackoverflow.com/questions/tagged/nexmo)."
              type: large
            - content: "Your data will be treated in accordance with our [Privacy Policy](https://www.nexmo.com/privacy-policy), which sets out the rights you have in respect of your data."
              type: large
